WIP: Primary udn integration
kubevirt/ipam-extensions pull request #59
Opened 2024-08-26 15:03 UTC by maiqueb

**What this PR does / why we need it**:
This PR instructs OVN-K of the IPAMClaim name to be used for the primary UDN feature.

We could have hard-coded instead the name, but then, we would need to understand which workload really wants persistent IPs on OVN-K - i.e. it would have to identify if it is allocating for a VM or a pod.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
WIP. PLEASE DO NOT merge.

**Release note**:

```release-note
Integrate with the primary user defined network OVN-Kubernetes feature.
```

2024-08-26 15:05 UTC, oshoval commented
to review it or it is wip ?
confused

2024-08-26 15:13 UTC, maiqueb commented
> to review it or it is wip ? confused

WIP

2024-09-02 14:56 UTC, qinqon requested changes
First pass, normalize ipam claim key generation.

2024-09-02 14:56 UTC, qinqon commented on pkg/vminetworkscontroller/vmi_controller.go
> +		claimKey := fmt.Sprintf("%s.%s-primary-udn", vmi.Name, primaryUDN.Name)
We should normalize the key to follow k8s naming conventions, I have see errors like the following when the network name at the NAD has unexpected chars.

```
 Retry add failed for *v1.Pod kv-live-migration-8805/virt-launcher-worker1-987pq, will try again later: failed to update pod kv-live-migration-8805/virt-launcher-worker1-987pq: error retrieving IPAMClaim for pod kv-live-migration-8805/virt-launcher-worker1-987pq: failed to get IPAMClaim "worker1.jv45k_net1-primary-udn": ipamclaim.k8s.cni.cncf.io "worker1.jv45k_net1-primary-udn" not found
```

2024-09-02 15:03 UTC, maiqueb commented
Abandoned in-lieu of #36 .

Didn't notice that PR existed, sorry about that.

2024-09-02 15:03 UTC, closed without merging