spike: Run e2e tests in paralel
kubevirt/ipam-extensions pull request #76
Opened 2024-11-21 11:32 UTC by RamLavi

**What this PR does / why we need it**:
This PR is running the e2e tests in parallel, as tests should be independent of each other. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2024-12-19 09:59 UTC, RamLavi commented
@maiqueb looking at the e2e test failing, it seems like **prior** (and also after) to migration the primary UDN virt-launcher pod is not getting the appropriate network-status ([logs](https://github.com/kubevirt/ipam-extensions/actions/runs/12389423766/job/34582420134?pr=76#step:7:369)):
```
2024-12-18T09:08:33.5592345Z   RAM B4 Migration vmi alpine-908896f1e virtLauncherPod virt-launcher-alpine-908896f1e-h2nb9 Annotations map[descheduler.alpha.kubernetes.io/request-evict-only: k8s.ovn.org/pod-networks:{"default":{"ip_addresses":["10.244.1.15/24","fd00:10:244:2::f/64"],"mac_address":"0a:58:0a:f4:01:0f","gateway_ips":["10.244.1.1","fd00:10:244:2::1"],"routes":[{"dest":"10.244.0.0/16","nextHop":"10.244.1.1"},{"dest":"10.96.0.0/16","nextHop":"10.244.1.1"},{"dest":"169.254.0.5/32","nextHop":"10.244.1.1"},{"dest":"100.64.0.0/16","nextHop":"10.244.1.1"},{"dest":"fd00:10:244::/48","nextHop":"fd00:10:244:2::1"},{"dest":"fd00:10:96::/112","nextHop":"fd00:10:244:2::1"},{"dest":"fd69::5/128","nextHop":"fd00:10:244:2::1"},{"dest":"fd98::/64","nextHop":"fd00:10:244:2::1"}],"role":"primary"},"testns-30ce1396d/l2-net-attach-def":{"ip_addresses":["10.100.200.3/24"],"mac_address":"0a:58:0a:64:c8:03","gateway_ips":["10.100.200.1"],"routes":[{"dest":"10.96.0.0/16","nextHop":"10.100.200.1"},{"dest":"100.65.0.0/16","nextHop":"10.100.200.1"}],"ip_address":"10.100.200.3/24","gateway_ip":"10.100.200.1","tunnel_id":4,"role":"primary"}} k8s.ovn.org/primary-udn-ipamclaim:alpine-908896f1e.pod k8s.v1.cni.cncf.io/network-status:[{
2024-12-18T09:08:33.5597745Z       "name": "ovn-kubernetes",
2024-12-18T09:08:33.5598207Z       "interface": "eth0",
2024-12-18T09:08:33.5598567Z       "ips": [
2024-12-18T09:08:33.5598959Z           "10.244.1.15",
2024-12-18T09:08:33.5599436Z           "fd00:10:244:2::f"
2024-12-18T09:08:33.5599819Z       ],
2024-12-18T09:08:33.5600197Z       "mac": "0a:58:0a:f4:01:0f",
2024-12-18T09:08:33.5600463Z       "default": true,
2024-12-18T09:08:33.5600668Z       "dns": {}
2024-12-18T09:08:33.5603199Z   }] kubectl.kubernetes.io/default-container:compute kubevirt.io/domain:alpine-908896f1e kubevirt.io/migrationTransportUnix:true kubevirt.io/vm-generation:1 post.hook.backup.velero.io/command:["/usr/bin/virt-freezer", "--unfreeze", "--name", "alpine-908896f1e", "--namespace", "testns-30ce1396d"] post.hook.backup.velero.io/container:compute pre.hook.backup.velero.io/command:["/usr/bin/virt-freezer", "--freeze", "--name", "alpine-908896f1e", "--namespace", "testns-30ce1396d"] pre.hook.backup.velero.io/container:compute]
2024-12-18T09:08:33.5606414Z 
```


Can we attribute this issue to the OVNK race you talked about? OR is it a new issue we need to check?

2024-12-19 12:08 UTC, maiqueb commented
> @maiqueb looking at the e2e test failing, it seems like **prior** (and also after) to migration the primary UDN virt-launcher pod is not getting the appropriate network-status ([logs](https://github.com/kubevirt/ipam-extensions/actions/runs/12389423766/job/34582420134?pr=76#step:7:369)):
> 
> ```
> 2024-12-18T09:08:33.5592345Z   RAM B4 Migration vmi alpine-908896f1e virtLauncherPod virt-launcher-alpine-908896f1e-h2nb9 Annotations map[descheduler.alpha.kubernetes.io/request-evict-only: k8s.ovn.org/pod-networks:{"default":{"ip_addresses":["10.244.1.15/24","fd00:10:244:2::f/64"],"mac_address":"0a:58:0a:f4:01:0f","gateway_ips":["10.244.1.1","fd00:10:244:2::1"],"routes":[{"dest":"10.244.0.0/16","nextHop":"10.244.1.1"},{"dest":"10.96.0.0/16","nextHop":"10.244.1.1"},{"dest":"169.254.0.5/32","nextHop":"10.244.1.1"},{"dest":"100.64.0.0/16","nextHop":"10.244.1.1"},{"dest":"fd00:10:244::/48","nextHop":"fd00:10:244:2::1"},{"dest":"fd00:10:96::/112","nextHop":"fd00:10:244:2::1"},{"dest":"fd69::5/128","nextHop":"fd00:10:244:2::1"},{"dest":"fd98::/64","nextHop":"fd00:10:244:2::1"}],"role":"primary"},"testns-30ce1396d/l2-net-attach-def":{"ip_addresses":["10.100.200.3/24"],"mac_address":"0a:58:0a:64:c8:03","gateway_ips":["10.100.200.1"],"routes":[{"dest":"10.96.0.0/16","nextHop":"10.100.200.1"},{"dest":"100.65.0.0/16","nextHop":"10.100.200.1"}],"ip_address":"10.100.200.3/24","gateway_ip":"10.100.200.1","tunnel_id":4,"role":"primary"}} k8s.ovn.org/primary-udn-ipamclaim:alpine-908896f1e.pod k8s.v1.cni.cncf.io/network-status:[{
> 2024-12-18T09:08:33.5597745Z       "name": "ovn-kubernetes",
> 2024-12-18T09:08:33.5598207Z       "interface": "eth0",
> 2024-12-18T09:08:33.5598567Z       "ips": [
> 2024-12-18T09:08:33.5598959Z           "10.244.1.15",
> 2024-12-18T09:08:33.5599436Z           "fd00:10:244:2::f"
> 2024-12-18T09:08:33.5599819Z       ],
> 2024-12-18T09:08:33.5600197Z       "mac": "0a:58:0a:f4:01:0f",
> 2024-12-18T09:08:33.5600463Z       "default": true,
> 2024-12-18T09:08:33.5600668Z       "dns": {}
> 2024-12-18T09:08:33.5603199Z   }] kubectl.kubernetes.io/default-container:compute kubevirt.io/domain:alpine-908896f1e kubevirt.io/migrationTransportUnix:true kubevirt.io/vm-generation:1 post.hook.backup.velero.io/command:["/usr/bin/virt-freezer", "--unfreeze", "--name", "alpine-908896f1e", "--namespace", "testns-30ce1396d"] post.hook.backup.velero.io/container:compute pre.hook.backup.velero.io/command:["/usr/bin/virt-freezer", "--freeze", "--name", "alpine-908896f1e", "--namespace", "testns-30ce1396d"] pre.hook.backup.velero.io/container:compute]
> 2024-12-18T09:08:33.5606414Z 
> ```
> 
> Can we attribute this issue to the OVNK race you talked about? OR is it a new issue we need to check?

It could be. 

You'll need to check the logs of the ovnkube-control plane and ensure that for that pod it failed to find the primary UDN network to be sure.

2024-12-19 13:32 UTC, maiqueb commented
> > > @maiqueb looking at the e2e test failing, it seems like **prior** (and also after) to migration the primary UDN virt-launcher pod is not getting the appropriate network-status ([logs](https://github.com/kubevirt/ipam-extensions/actions/runs/12389423766/job/34582420134?pr=76#step:7:369)):
> > > ```
> > > 2024-12-18T09:08:33.5592345Z   RAM B4 Migration vmi alpine-908896f1e virtLauncherPod virt-launcher-alpine-908896f1e-h2nb9 Annotations map[descheduler.alpha.kubernetes.io/request-evict-only: k8s.ovn.org/pod-networks:{"default":{"ip_addresses":["10.244.1.15/24","fd00:10:244:2::f/64"],"mac_address":"0a:58:0a:f4:01:0f","gateway_ips":["10.244.1.1","fd00:10:244:2::1"],"routes":[{"dest":"10.244.0.0/16","nextHop":"10.244.1.1"},{"dest":"10.96.0.0/16","nextHop":"10.244.1.1"},{"dest":"169.254.0.5/32","nextHop":"10.244.1.1"},{"dest":"100.64.0.0/16","nextHop":"10.244.1.1"},{"dest":"fd00:10:244::/48","nextHop":"fd00:10:244:2::1"},{"dest":"fd00:10:96::/112","nextHop":"fd00:10:244:2::1"},{"dest":"fd69::5/128","nextHop":"fd00:10:244:2::1"},{"dest":"fd98::/64","nextHop":"fd00:10:244:2::1"}],"role":"primary"},"testns-30ce1396d/l2-net-attach-def":{"ip_addresses":["10.100.200.3/24"],"mac_address":"0a:58:0a:64:c8:03","gateway_ips":["10.100.200.1"],"routes":[{"dest":"10.96.0.0/16","nextHop":"10.100.200.1"},{"dest":"100.65.0.0/16","nextHop":"10.100.200.1"}],"ip_address":"10.100.200.3/24","gateway_ip":"10.100.200.1","tunnel_id":4,"role":"primary"}} k8s.ovn.org/primary-udn-ipamclaim:alpine-908896f1e.pod k8s.v1.cni.cncf.io/network-status:[{
> > > 2024-12-18T09:08:33.5597745Z       "name": "ovn-kubernetes",
> > > 2024-12-18T09:08:33.5598207Z       "interface": "eth0",
> > > 2024-12-18T09:08:33.5598567Z       "ips": [
> > > 2024-12-18T09:08:33.5598959Z           "10.244.1.15",
> > > 2024-12-18T09:08:33.5599436Z           "fd00:10:244:2::f"
> > > 2024-12-18T09:08:33.5599819Z       ],
> > > 2024-12-18T09:08:33.5600197Z       "mac": "0a:58:0a:f4:01:0f",
> > > 2024-12-18T09:08:33.5600463Z       "default": true,
> > > 2024-12-18T09:08:33.5600668Z       "dns": {}
> > > 2024-12-18T09:08:33.5603199Z   }] kubectl.kubernetes.io/default-container:compute kubevirt.io/domain:alpine-908896f1e kubevirt.io/migrationTransportUnix:true kubevirt.io/vm-generation:1 post.hook.backup.velero.io/command:["/usr/bin/virt-freezer", "--unfreeze", "--name", "alpine-908896f1e", "--namespace", "testns-30ce1396d"] post.hook.backup.velero.io/container:compute pre.hook.backup.velero.io/command:["/usr/bin/virt-freezer", "--freeze", "--name", "alpine-908896f1e", "--namespace", "testns-30ce1396d"] pre.hook.backup.velero.io/container:compute]
> > > 2024-12-18T09:08:33.5606414Z 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Can we attribute this issue to the OVNK race you talked about? OR is it a new issue we need to check?
> > 
> > 
> > It could be.
> > You'll need to check the logs of the ovnkube-control plane and ensure that for that pod it failed to find the primary UDN network to be sure.
> 
> I don't see any pod fails, but are you sure we should find a "pod fail"? I mean, it did find a primary network, it was just the wrong one.. In any case, this is very helpful, I've also asked on the race bug to know more information..

So that's what you need to find: when it returns the active network for the namespace, which one did it find ? 

It should have found the primary UDN, not the default one. Can you print the relevant logs here ?

2024-12-31 20:00 UTC, RamLavi commented
After some digging on OVNK, I realized the network is being reconciled. The reason is that the network name in the tests is the same. In order to separate the test and run them in parallel - I changed the network names to be unique.

2025-01-08 11:23 UTC, maiqueb requested changes
Seems OK to me, but I wonder if / how we can still indicate which tests we want to run.

2025-01-08 13:28 UTC, RamLavi commented on Makefile
> +	$(GINKGO) -v --timeout=${E2E_TEST_TIMEOUT} --junit-report=$${REPORT_PATH}/test-e2e.junit.xml
You're right. I re-introduced the E2E_TEST_ARGS flag.
[DONE](https://github.com/kubevirt/ipam-extensions/compare/127686b03a91c2c3480b670b1ade2183c327f7a5..2b47b7d216f1cf0e3fbe54ef13e263e89f9b72de)

2025-01-08 13:29 UTC, RamLavi commented
[Change](https://github.com/kubevirt/ipam-extensions/compare/127686b03a91c2c3480b670b1ade2183c327f7a5..2b47b7d216f1cf0e3fbe54ef13e263e89f9b72de): re-introduced the E2E_TEST_ARGS flag.

2025-01-08 13:29 UTC, RamLavi commented
[Change](https://github.com/kubevirt/ipam-extensions/compare/2b47b7d216f1cf0e3fbe54ef13e263e89f9b72de..314f4743670ac970ddb2e91975b36f231f8f9cee): Rebase

2025-01-08 13:29 UTC, maiqueb reviewed
@RamLavi did you check this does the trick locally ? 

No way it shouldn't afaict, but still, please paste an example of how to invoke it both in the appropriate commit msg and in the PR's description. 

Thank you !

2025-01-08 13:31 UTC, RamLavi commented
> @RamLavi did you check this does the trick locally ?

I run it on zeus33. good enough right?

> No way it shouldn't afaict, but still, please paste an example of how to invoke it both in the appropriate commit msg and in the PR's description.

The usage is the same: `make test-e2e`. Should I mention it?

2025-01-08 13:35 UTC, maiqueb commented
> > @RamLavi did you check this does the trick locally ?
> 
> I run it on zeus33. good enough right?
> 
> > No way it shouldn't afaict, but still, please paste an example of how to invoke it both in the appropriate commit msg and in the PR's description.
> 
> The usage is the same: `make test-e2e`. Should I mention it?

I mean regarding the flag. If you want to filter some tests, do you need to use a different flag ? Can you check locally if you need to ? I have the slight recollection it isn't exactly the same command. BUT I might be wrong.

@qinqon could you chime in here ? Thanks in advance.

2025-01-08 21:41 UTC, maiqueb commented
> > > > @RamLavi did you check this does the trick locally ?
> > > 
> > > 
> > > I run it on zeus33. good enough right?
> > > > No way it shouldn't afaict, but still, please paste an example of how to invoke it both in the appropriate commit msg and in the PR's description.
> > > 
> > > 
> > > The usage is the same: `make test-e2e`. Should I mention it?
> > 
> > 
> > I mean regarding the flag. If you want to filter some tests, do you need to use a different flag ? Can you check locally if you need to ? I have the slight recollection it isn't exactly the same command. BUT I might be wrong.
> > @qinqon could you chime in here ? Thanks in advance.
> 
> Using the general `E2E_TEST_ARGS` env var allows us to add whatever flags we wish. For ginkgo the relevant flags are `--skip` and `--focus`. I tried focus and it works:
> 
> ```
> # E2E_TEST_ARGS='--focus="should keep ips after live migration"' make test-e2e
> export KUBECONFIG=/root/github.com/kubevirt/ipam-extensions/.output/kubeconfig && \
> export PATH=$(pwd)/.output/ovn-kubernetes/bin:${PATH} && \
> export REPORT_PATH=$(pwd)/.output/ && \
> cd test/e2e && \
> /root/github.com/kubevirt/ipam-extensions/bin/ginkgo-v2.22.0 -v --timeout="1h" --junit-report=${REPORT_PATH}/test-e2e.junit.xml --focus='"should keep ips after live migration"'
> ...
> Will run 4 of 20 specs
> ...
> ```
> 
> but that's not a new env var.

Sure, but for us to keep it's current behavior, the value in it must now be different.

All good. Could you add this `E2E_TEST_ARGS='--focus="should keep ips after live migration"' make test-e2e` cmd to the PR description *and* the git commit msg ? 

Then, lgtm / approve / merge :)

2025-01-09 07:30 UTC, RamLavi commented
Change: Updated commit desc

2025-01-09 08:29 UTC, maiqueb approved these changes
/approve

Thank you.

2025-01-09 08:29 UTC, maiqueb commented
/hold

2025-01-09 08:36 UTC, maiqueb commented on test/env/generate.go
> +	networkName := strings.Join([]string{"l2", role, rand.String(randCharacters)}, "-")
I wonder if there are any chances of a collision here ...

I almost feel silly asking, but, shouldn't we cover against that ? 

Anyway ... I'm willing to try this out as is. We can adapt once we ever see a collision.

@RamLavi feel free to lift the hold I've set in another comment.

2025-01-09 09:04 UTC, RamLavi commented on test/env/generate.go
> +	networkName := strings.Join([]string{"l2", role, rand.String(randCharacters)}, "-")
IIUC rand.String(n) produces a set of n random characters. Avoiding vowels for some reason - each character can be one of 27. So chance of collison is 1/27^n  = 1/27^5 = 1/14,348,907 = 0.00000697%. We can live with that.

2025-01-09 09:04 UTC, RamLavi commented
/hold cancel

2025-01-09 09:06 UTC, merged